from apps.local_settings import *

SECRET_KEY = SECRET_KEY

ALGORITHM = ALGORITHM

ACCESS_TOKEN_EXPIRE_MINUTES = ACCESS_TOKEN_EXPIRE_MINUTES

REFRESH_EXPIRE_DAYS = REFRESH_EXPIRE_DAYS

ITERATIONS = ITERATIONS
