# Subdomain: yasin.kioteam.ir
upstream yasin_upstream {
    server frontend-resume_website:5000;
}

server {
    listen 80;
    listen [::]:80;
    server_name yasin.kioteam.ir;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name yasin.kioteam.ir;

    ssl_certificate     /etc/letsencrypt/live/yasin.kioteam.ir/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/yasin.kioteam.ir/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;

    limit_req zone=general_limit burst=20 nodelay;

    access_log /var/log/nginx/yasin.access.log main;
    error_log  /var/log/nginx/yasin.error.log;

    location / {
        proxy_pass http://yasin_upstream;
        include /etc/nginx/snippets/proxy-params.conf;
    }
}
