"""post author fk, updated_at, status index

Revision ID: 63c72fd4e46d
Revises: 2e2353f84e2d
Create Date: 2026-09-23 22:36:48.225449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c72fd4e46d'
down_revision: Union[str, Sequence[str], None] = '2e2353f84e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add updated_at as nullable, backfill existing rows from created_at,
    # then convert both timestamps to timestamptz (asyncpg rejects aware
    # datetimes written to naive timestamp columns) and enforce NOT NULL.
    op.add_column('blog_post', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute('UPDATE blog_post SET updated_at = created_at')
    op.alter_column(
        'blog_post',
        'updated_at',
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        nullable=False,
        postgresql_using="updated_at AT TIME ZONE 'UTC'",
    )
    # created_at was a naive timestamp fed with UTC-aware datetimes, which
    # asyncpg rejects; move it to timestamptz so stored values keep their zone.
    op.alter_column(
        'blog_post',
        'created_at',
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        postgresql_using="created_at AT TIME ZONE 'UTC'",
    )
    op.create_index('ix_blog_post_status_created_at', 'blog_post', ['status', 'created_at'], unique=False)
    op.create_foreign_key(
        'fk_blog_post_author_id_accounts_user',
        'blog_post',
        'accounts_user',
        ['author_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_blog_post_author_id_accounts_user', 'blog_post', type_='foreignkey')
    op.drop_index('ix_blog_post_status_created_at', table_name='blog_post')
    op.drop_column('blog_post', 'updated_at')
    op.alter_column(
        'blog_post',
        'created_at',
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        postgresql_using="created_at AT TIME ZONE 'UTC'",
    )
    # ### end Alembic commands ###