services:
  api:
    restart: always
    environment:
      DEBUG: "false"
    deploy:
      resources:
        limits:
          cpus: ".5"
          memory: 0.5G

  web:
    restart: always
    deploy:
      resources:
        limits:
          cpus: ".2"
          memory: 256M

  db:
    restart: always

  redis:
    restart: always
